### ISSUE TITLE
コンソールからconnectコマンドを発行することはできないのでしょうか？

### ISSUE THREAD

**Issue by kairi-2525** [tutinoko2048/discord-mcbe#20]
コンソールからconnectコマンドを発行することはできないのでしょうか？
自分の環境だとコンソールからは使えず、ゲーム側で実行し、その実行したクライアントがサーバーに常に参加していないと動かない状態ですが、そういった仕様なのでしょうか？

**Comment by tutinoko2048** [comment]
マイクラの仕様的に外部からのトリガーで接続することはできません...
Websocketはワールドではなくクライアント側に接続するものなので常に鯖に入っておく必要があります
