### ISSUE TITLE
undefined error version2.2.0

### ISSUE THREAD

**Issue by ZakGhost354313** [tutinoko2048/discord-mcbe#21]
![image](https://user-images.githubusercontent.com/68399876/189454613-742a2160-cf29-4d4e-a1cc-c4b0d51fd6f8.png)
I get this error when I run the `start.cmd` command

**Comment by tutinoko2048** [comment]
Did you write channel id in config.json?
This is an error that occurs when the channel could not be got.
not channel name but id

**Comment by ZakGhost354313** [comment]
I’ll check when I get back to my laptop
